import type { Metadata } from "next";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { getAuthUser } from "@/lib/get-auth-user";
import { AuthProvider } from "@/hooks/useAuthUser";
import Navbar from "@/components/main/Navbar";

export const inter = Inter({ subsets: ["latin"], variable: "--font-body" });

export const poppins = Poppins({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getAuthUser();
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased bg-bg`}
      >
        <AuthProvider user={user}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
